# Generated by Django 3.0.4 on 2020-04-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='usr',
            new_name='user',
        ),
    ]
